# -*- coding: utf-8 -*-
{
    'name': 'Theme Agency',
    'summary': "Theme Agency Page for About Agency, Customers, Pricing, Service Agency",
    'version': '1.1',
    'category': 'Website',
    'author': 'Bansi',
    'depends': ['base', 'website', 'portal','website_sale','website_event','website_blog'],
    'data': [
        'views/assets.xml',
        'views/header.xml',
        'views/snippet.xml',
        'views/footer.xml',
        'views/login.xml',
        'views/about-agency.xml',
        'views/customers.xml',
        'views/customer-story.xml',
        'views/pricing.xml',
        'views/services-agency.xml',
        'views/terms.xml',
        'views/landing-app-saas.xml',
        'views/landing-app-workflow.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}
